# Phase 8E v2: Parent-Child Markdown Splitter (Larger Parent Context)
# Goal: Test hybrid approach with larger parent threshold
#
# Baseline: Exp6 (Recursive, chunk=500) → Precision 0.783
# Phase 8C failed: Pure Markdown (18 tiny chunks, -17% precision)
#
# New approach (from Claude insights):
#   - Parent: Markdown sections split on ##
#   - Child: RecursiveCharacter split if parent > threshold
#   - Store: child for retrieval, parent metadata for context
#
# Variant 2 (This config): Larger parent threshold
#   - parent_max_tokens: 1500 (preserve more context)
#   - child_chunk_size: 450 (slightly smaller for precision)
#
# Expected Results:
# - Fewer splits → more context preserved
# - Potentially higher recall (complete sections kept intact)
# - Trade-off: May have lower precision vs v1

domain_name: z3_agent_exp8e_v2

knowledge_base_dir: docs/
vector_store_dir: data/vector_stores/z3_agent_exp8e_v2/
golden_dataset: golden_datasets/z3_agent_tests.json

personality_config_path: content/reply_config1.json
supervisor_prompt_path: content/supervisor-prompt.txt

# Embedding: MPNet (proven winner from Phase 8)
embedding_model: sentence-transformers/paraphrase-multilingual-mpnet-base-v2

llm_model: gemini-2.0-flash
llm_temperature: 0.7

# RAG parameters
relevance_threshold: 0.3
retrieval_k: 3

# Parent-Child Markdown Splitter Parameters (Larger parent variant)
use_parent_child_splitter: true
parent_headers_to_split: ["##"]  # Split on level 2 headers only
parent_max_tokens: 1500          # ← Larger threshold: preserve more context
child_chunk_size: 450            # ← Slightly smaller for precision
child_chunk_overlap: 50
